name: ActionWorkFlowCommandTest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Environment
      run: | 
        env 
        
    - name: Build
      run: dotnet build GitHubTestLogger.sln --configuration Debug
      
  test-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --logger "github;report-warnings=false;GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" -c Debug

