name: Release
on:
  release:
    types: [published]
  push:           #TEST emulate release on push on master
    branches:     #TEST emulate release on push on master
      - master    #TEST emulate release on push on master

jobs:
  build:
    env:
      CONFIGURATION: Release
      BUILDPATH: src/GitHubTestLogger
      NUPKGPATH: packages
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: REL_*
      run: | 
        REL_GITHUB_REF=$GITHUB_REF
        echo '::set-env name=REL_GITHUB_REF::'$GITHUB_REF
        REL_GITHUB_REF="refs/tags/v0.0.1-alpha$GITHUB_RUN_NUMBER" #TEST emulate release on push on master
        echo '::set-env name=REL_GITHUB_REF::'$REL_GITHUB_REF     #TEST emulate release on push on master
        REL_VERSION="${REL_GITHUB_REF/refs\/tags\/v/}"  
        echo '::set-env name=REL_VERSION::'$REL_VERSION
        REL_VERSION_ONLY=$( echo "$REL_VERSION" | cut -d\- -f1) 
        echo '::set-env name=REL_VERSION_ONLY::'$REL_VERSION_ONLY
      
    - name: debug/test
      run: | 
        env
        
    - name: Build
      run: dotnet build $BUILDPATH --configuration $CONFIGURATION
  
    - name: Pack
      run: |
        CMD="dotnet pack $BUILDPATH \
        --configuration $CONFIGURATION \
        --include-symbols \
        --include-source \
        -p:IncludeSymbols=true \
        -p:SymbolPackageFormat=snupkg \
        /p:Version=$REL_VERSION \
        /p:RepositoryCommit=$GITHUB_SHA \
        /p:AssemblyVersion=$REL_VERSION_ONLY \
        /p:FileVersion=$REL_VERSION_ONLY \
        -o $NUPKGPATH"
        echo $CMD
        ${CMD}


#    - name: GPR NuGet config
#      shell: bash
#      env:
#        WORKSPACE: ${{ github.workspace }}
#      run: |
#        echo ::set-env name=GH_SHORT_SHA::"`git rev-parse --short "$GITHUB_SHA"`"
#        mv github_nuget.config nuget.config
#        sed -i.bak 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' nuget.config; rm nuget.config.bak
            
#    - name: Publish packages to GPR
#      run: | 
#        ls packages/*.*nupkg
#        dotnet nuget push 'packages/*.nupkg' --skip-duplicate --source "github" -k ${{secrets.GITHUB_TOKEN}}
    
    - name: Publish packages to NuGet.org
      run: |
        dotnet nuget push $NUPKGPATH'/*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}
        
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Test
#      run: dotnet test --logger "github;report-warnings=false;GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" -c Debug

