name: Release
on:
  release:
    types: [published]
  push:           #emulate release on push on master
    branches:     #emulate release on push on master
      - master    #emulate release on push on master

jobs:
  build:
    env:
      CONFIGURATION: Release
      BUILDPATH: src/GitHubTestLogger
      NUPKGPATH: packages
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: REL_VERSION
      run: | 
        REL_VERSION="${GITHUB_REF/refs\/tags\/v/}"  
        echo '::set-env name=REL_VERSION::'$REL_VERSION
        REL_VERSION_ONLY=$( echo "$REL_VERSION" | cut -d\- -f1) 
        echo '::set-env name=REL_VERSION_ONLY::'$REL_VERSION_ONLY
      
    - name: debug/test
      run: | 
        env
        
    - name: Build
      run: dotnet build $BUILDPATH --configuration $CONFIGURATION
  
    - name: Pack
      run: |
        dotnet pack $BUILDPATH --configuration $CONFIGURATION \
                               --include-symbols \ 
                               --include-source \ 
                               -p:IncludeSymbols=true \ 
                               -p:SymbolPackageFormat=snupkg \ 
                               /p:Version=$REL_VERSION \ 
                               /p:RepositoryCommit=$GITHUB_SHA \
                               /p:AssemblyVersion=$REL_VERSION
                                   <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
                               -o $NUPKGPATH
#        
#    - name: GPR NuGet config
#      shell: bash
#      env:
#        WORKSPACE: ${{ github.workspace }}
#      run: |
#        echo ::set-env name=GH_SHORT_SHA::"`git rev-parse --short "$GITHUB_SHA"`"
#        mv github_nuget.config nuget.config
#        sed -i.bak 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' nuget.config; rm nuget.config.bak
            
#    - name: Publish packages to GPR
#      run: | 
#        ls packages/*.*nupkg
#        dotnet nuget push 'packages/*.nupkg' --skip-duplicate --source "github" -k ${{secrets.GITHUB_TOKEN}}
    
#    - name: Publish packages to NuGet.org
#      run: |
#        dotnet nuget push 'packages/*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}
        
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Test
#      run: dotnet test --logger "github;report-warnings=false;GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" -c Debug

